Random Variables

In [2]:
import numpy as np
from sklearn.datasets import load_iris

#loading the iris dataset
iris = load_iris()
data = iris.data

#defining random variables
random_variables_indices = [0, 1, 2, 3] #indices of features: sepal length, sepal width, petal length, petal width
random_variables = []
for index in random_variables_indices:
    random_variables.append(data[:, index])
for i, variable in enumerate(random_variables):
    print(f"random variable {i+1} (feature {random_variables_indices[i]}):")
    print(variable[:10])
    print()





random variable 1 (feature 0):
[5.1 4.9 4.7 4.6 5.  5.4 4.6 5.  4.4 4.9]

random variable 2 (feature 1):
[3.5 3.  3.2 3.1 3.6 3.9 3.4 3.4 2.9 3.1]

random variable 3 (feature 2):
[1.4 1.4 1.3 1.5 1.4 1.7 1.4 1.5 1.4 1.5]

random variable 4 (feature 3):
[0.2 0.2 0.2 0.2 0.2 0.4 0.3 0.2 0.2 0.1]



Binomial Theorem

In [5]:
#Binomial Theorem
import numpy as np
from sklearn.datasets import load_iris
from scipy.stats import binom

#loading iris dataset
iris = load_iris()
target = iris.target

#define binary feature based on sepal length
threshold_sepal_length = 5.5
binary_feature = (iris.data[:, 0] > threshold_sepal_length).astype(int)

#count the occurrences of iris setosa for the binary feature
count_successes = np.sum((binary_feature == 1) & (target == 0))

#total number of trials (number of iris flowers)
total_trials = len(iris.data)


#success probability : flower being setosa
p_success = count_successes / total_trials


#define the number of trials
n_trials = 50

#binomial distribution calculation
binomial_dist = binom(n_trials, p_success)

print("Binomial Distribution: ")
for i in range(n_trials + 1):
    print(f"probability of {i} successes: {binomial_dist.pmf(i)}")


Binomial Distribution: 
probability of 0 successes: 0.36416968008711675
probability of 1 successes: 0.37160171437460954
probability of 2 successes: 0.18580085718730477
probability of 3 successes: 0.060669667652997375
probability of 4 successes: 0.014548338671892216
probability of 5 successes: 0.0027315248118654854
probability of 6 successes: 0.0004180905324283901
probability of 7 successes: 5.363260474300058e-05
probability of 8 successes: 5.883168377420997e-06
probability of 9 successes: 5.603017502305686e-07
probability of 10 successes: 4.688239134582297e-08
probability of 11 successes: 3.479212715831026e-09
probability of 12 successes: 2.3076410870307814e-10
probability of 13 successes: 1.37661477719262e-11
probability of 14 successes: 7.42489019768611e-13
probability of 15 successes: 3.636680913152395e-14
probability of 16 successes: 1.623518264800171e-15
probability of 17 successes: 6.626605162449684e-17
probability of 18 successes: 2.479342067583217e-18
probability of 19 successe